"""One generated byte suffix, reconciled with both native token vocabularies."""
from __future__ import annotations

from dataclasses import dataclass
import numpy as np


@dataclass
class VocabularySurfaces:
    pieces: tuple[bytes, ...]
    flags: tuple[int, ...]
    byte_tokens: dict[int, int]


def inspect_surfaces(native):
    result = []
    for brain in (0, 1):
        pieces, flags, byte_tokens = [], [], {}
        for token in range(native.geometry[brain]['vocab']):
            flag = native.token_flags(brain, token)
            piece = b'' if flag else native.piece(brain, token)
            pieces.append(piece)
            flags.append(flag)
            if len(piece) == 1:
                byte_tokens.setdefault(piece[0], token)
        result.append(VocabularySurfaces(tuple(pieces), tuple(flags), byte_tokens))
    return result


def native_alignment(surfaces):
    from .alignment import ExactSurfaceAlignment
    n, k = surfaces
    k_ids = {}
    for token, piece in enumerate(k.pieces):
        if piece and not k.flags[token]:
            k_ids.setdefault(piece, token)
    pairs = [(token, k_ids[piece]) for token, piece in enumerate(n.pieces)
             if piece and not n.flags[token] and piece in k_ids]
    return ExactSurfaceAlignment([pair[0] for pair in pairs], [pair[1] for pair in pairs], len(n.pieces), len(k.pieces))


def split_utf8_prefix(value: bytes):
    try:
        return value.decode('utf-8'), b''
    except UnicodeDecodeError as error:
        if error.reason != 'unexpected end of data' or error.end != len(value):
            raise ValueError('Generated byte suffix is not a valid UTF-8 prefix') from error
        return value[:error.start].decode('utf-8'), value[error.start:]


class CanonicalPrefixes:
    def __init__(self, native, prefixes):
        self.native, self.prefixes = native, prefixes
        self.byte_tokens = [None, None]

    def _bytes(self, brain):
        if self.byte_tokens[brain] is None:
            if hasattr(self.native, 'surfaces'):
                self.byte_tokens[brain] = self.native.surfaces()[brain].byte_tokens
                return self.byte_tokens[brain]
            lookup = {}
            for token in range(self.native.geometry[brain]['vocab']):
                if self.native.token_flags(brain, token):
                    continue
                piece = self.native.piece(brain, token)
                if len(piece) == 1:
                    lookup.setdefault(piece[0], token)
            self.byte_tokens[brain] = lookup
        return self.byte_tokens[brain]

    def encode(self, suffix: bytes):
        complete, pending = split_utf8_prefix(suffix)
        result = []
        for brain in (0, 1):
            # These prefixes already contain their GGUF template's BOS and
            # role controls. Parse those controls without adding another BOS.
            ids = self.native.tokenize(brain, self.prefixes[brain] + complete, special=False)
            if pending:
                lookup = self._bytes(brain)
                if any(byte not in lookup for byte in pending):
                    raise ValueError('Both native vocabularies must represent the pending UTF-8 bytes exactly')
                ids = np.concatenate((ids, np.asarray([lookup[byte] for byte in pending], np.int32)))
            result.append(ids)
        return result
